#!/usr/bin/bash

█████████████████████████ <- redacted
████████████████████████████
███████████████████████████████████████████
██████████████████████████████████████████

████████████
██████████████████████
██████████████████████

#### You only need to edit the above redacted lines to use this slurm file ####
#### However, feel free to use your own slurm file if you prefer ##############

OMP_NUM_THREADS=2 ./build/run files/text1-ASCII.txt text1-ASCII.txt.test.01
